import { useState } from 'react'
import { CalendarPlus, CalendarX2, Pencil, Trash2, X } from 'lucide-react'
import CalendarView from '../components/CalendarView'
import OccupationTypeBadge from '../components/OccupationTypeBadge'
import NoteCategoryBadge from '../components/NoteCategoryBadge'
import PriorityBadge from '../components/PriorityBadge'
import ScheduleNoteModal from '../components/ScheduleNoteModal'
import { getBlockedSlots, getRequests, getTodos, saveBlockedSlots, saveTodos, uid } from '../utils/storage'
import { occupationTypes } from '../utils/occupationTypes'
import { calculateEndTime, formatLongDate, overlaps, toMinutes } from '../utils/timeUtils'

const empty={date:'',startTime:'09:00',endTime:'10:00',type:'class',title:'',privateComment:''}
export default function AvailabilityManager(){
  const [blocked,setBlocked]=useState(getBlockedSlots),[todos,setTodos]=useState(getTodos),[anchor,setAnchor]=useState(new Date()),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[error,setError]=useState(''),[noteModal,setNoteModal]=useState(false),[selectedNoteBlock,setSelectedNoteBlock]=useState(null),[moveNotice,setMoveNotice]=useState(null)
  const requests=getRequests()
  const persistBlocks=next=>{saveBlockedSlots(next);setBlocked(next)}
  const persistTodos=next=>{saveTodos(next);setTodos(next)}
  const submit=e=>{e.preventDefault();setError('');if(!form.date||!form.type||!form.title.trim())return setError('Date, occupation type, and title are required.');if(toMinutes(form.startTime)>=toMinutes(form.endTime))return setError('End time must be later than start time.');if(toMinutes(form.startTime)<480||toMinutes(form.endTime)>1140)return setError('Time must be within 08:00–19:00.');if(blocked.some(b=>b.id!==editing&&b.date===form.date&&overlaps(form.startTime,form.endTime,b.startTime,b.endTime)))return setError('This range overlaps another occupied block.');if(requests.some(r=>r.date===form.date&&r.status==='approved'&&overlaps(form.startTime,form.endTime,r.startTime,calculateEndTime(r.startTime,r.duration))))return setError('This range overlaps an approved meeting.');const now=new Date().toISOString(),existing=blocked.find(b=>b.id===editing),record={...form,title:form.title.trim(),source:'manual_block',linkedTodoId:null,priority:'medium',status:'planned',id:editing||uid(),createdAt:existing?.createdAt||now,updatedAt:now};persistBlocks(editing?blocked.map(b=>b.id===editing?record:b):[...blocked,record]);setForm(empty);setEditing(null)}
  const openScheduled=block=>{setSelectedNoteBlock(block);setNoteModal(true)}
  const closeScheduled=()=>{setNoteModal(false);setSelectedNoteBlock(null)}
  const edit=block=>{if(block.source?.startsWith('scheduled_'))return openScheduled(block);setEditing(block.id);setForm({date:block.date,startTime:block.startTime,endTime:block.endTime,type:block.type,title:block.title,privateComment:block.privateComment||''});window.scrollTo({top:0,behavior:'smooth'})}
  const cancel=()=>{setEditing(null);setForm(empty);setError('')}
  const deleteBlock=id=>{if(!confirm('Delete this occupied time?'))return;const block=blocked.find(b=>b.id===id),todo=todos.find(t=>t.id===block?.linkedTodoId);persistBlocks(blocked.filter(b=>b.id!==id));if(todo)persistTodos(todo.origin==='scheduled_note'?todos.filter(t=>t.id!==todo.id):todos.map(t=>t.id===todo.id?{...t,scheduledBlockId:null,scheduledDate:'',scheduledStartTime:'',scheduledEndTime:'',updatedAt:new Date().toISOString()}:t));if(editing===id)cancel();closeScheduled()}
  const saveScheduled=data=>{const now=new Date().toISOString(),existingBlock=selectedNoteBlock,existingTodo=todos.find(t=>t.id===existingBlock?.linkedTodoId),todoId=existingTodo?.id||uid(),blockId=existingBlock?.id||uid(),source=existingBlock?.source||'scheduled_note',todo={...(existingTodo||{}),id:todoId,title:data.title,description:data.description,category:data.category,priority:data.priority,status:data.status,dueDate:existingTodo?.dueDate||'',scheduledDate:data.date,scheduledStartTime:data.startTime,scheduledEndTime:data.endTime,estimatedDuration:data.duration,scheduledBlockId:blockId,origin:existingTodo?.origin||(source==='scheduled_todo'?'todo':'scheduled_note'),createdAt:existingTodo?.createdAt||now,updatedAt:now},block={...(existingBlock||{}),id:blockId,date:data.date,startTime:data.startTime,endTime:data.endTime,type:data.category,title:data.title,privateComment:data.description,priority:data.priority,status:data.status,source,linkedTodoId:todoId,createdAt:existingBlock?.createdAt||now,updatedAt:now};persistTodos(existingTodo?todos.map(t=>t.id===todoId?todo:t):[todo,...todos]);persistBlocks(existingBlock?blocked.map(b=>b.id===blockId?block:b):[...blocked,block]);closeScheduled()}
  const moveScheduled=(id,date,startTime)=>{const block=blocked.find(item=>item.id===id);if(!block?.source?.startsWith('scheduled_'))return;const duration=toMinutes(block.endTime)-toMinutes(block.startTime),endTime=calculateEndTime(startTime,duration);let text='';if(toMinutes(startTime)<480||toMinutes(endTime)>1140)text='Cannot move: the item must stay within 08:00–19:00.';else if(blocked.some(item=>item.id!==id&&item.date===date&&overlaps(startTime,endTime,item.startTime,item.endTime)))text='Cannot move: that time overlaps another occupied item.';else if(requests.some(r=>r.date===date&&r.status==='approved'&&overlaps(startTime,endTime,r.startTime,calculateEndTime(r.startTime,r.duration))))text='Cannot move: that time overlaps an approved meeting.';if(text){setMoveNotice({ok:false,text});setTimeout(()=>setMoveNotice(null),4000);return}const now=new Date().toISOString();persistBlocks(blocked.map(item=>item.id===id?{...item,date,startTime,endTime,updatedAt:now}:item));if(block.linkedTodoId)persistTodos(todos.map(todo=>todo.id===block.linkedTodoId?{...todo,scheduledDate:date,scheduledStartTime:startTime,scheduledEndTime:endTime,updatedAt:now}:todo));setMoveNotice({ok:true,text:`Moved “${block.title}” to ${date} at ${startTime}.`});setTimeout(()=>setMoveNotice(null),3000)}
  return <div className="dashboard-content">
    {moveNotice&&<div className={`page-toast ${moveNotice.ok?'success':'failure'}`}>{moveNotice.text}</div>}
    <div className="page-heading"><div><span className="eyebrow">Schedule settings</span><h1>Manage availability</h1><p>Private schedule details remain visible only in your teacher workspace. Drag scheduled notes to move them.</p></div><button className="btn btn-primary" onClick={()=>setNoteModal(true)}><CalendarPlus size={17}/>Add scheduled note</button></div>
    <div className="availability-layout"><section className="card block-form"><div className="card-heading"><div><span className="eyebrow">{editing?'Edit occupation':'New occupation'}</span><h2>{editing?'Update time block':'Block a time range'}</h2></div><CalendarX2/></div><form onSubmit={submit}><label>Date *<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><div className="field-grid"><label>Starts *<input type="time" step="300" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})}/></label><label>Ends *<input type="time" step="300" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})}/></label></div><label>Occupation type *<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{occupationTypes.map(t=><option value={t.value} key={t.value}>{t.label}</option>)}</select></label><label>Private title *<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Faculty meeting"/></label><label>Private comment<textarea rows="3" value={form.privateComment} onChange={e=>setForm({...form,privateComment:e.target.value})}/></label>{error&&<p className="field-error">{error}</p>}<button className="btn btn-secondary btn-wide">{editing?'Save changes':'Block this time'}</button>{editing&&<button type="button" className="btn btn-ghost btn-wide" onClick={cancel}><X size={16}/>Cancel editing</button>}</form>
      <div className="blocked-list"><h3>Occupied time</h3>{blocked.length===0?<p className="muted">No occupied time yet.</p>:[...blocked].sort((a,b)=>`${a.date}${a.startTime}`.localeCompare(`${b.date}${b.startTime}`)).map(b=><div className={`blocked-item ${b.source?.startsWith('scheduled_')?'scheduled-note-item':''}`} key={b.id}><div><strong>{b.title}</strong><span>{formatLongDate(b.date)} · {b.startTime}–{b.endTime}</span>{b.source?.startsWith('scheduled_')?<span className="note-badge-row"><NoteCategoryBadge category={b.type}/><PriorityBadge priority={b.priority}/>{b.status==='done'&&<span className="scheduled-badge">Done</span>}</span>:<OccupationTypeBadge type={b.type}/>} {b.privateComment&&<small>{b.privateComment}</small>}</div><span className="item-actions"><button onClick={()=>edit(b)} title="Edit"><Pencil size={16}/></button><button onClick={()=>deleteBlock(b.id)} title="Delete"><Trash2 size={16}/></button></span></div>)}</div></section>
      <div className="teacher-calendar"><CalendarView anchor={anchor} setAnchor={setAnchor} duration={30} blocked={blocked} requests={requests} teacher onTeacherBlockClick={edit} onMoveScheduledBlock={moveScheduled}/></div></div>
    {noteModal&&<ScheduleNoteModal note={todos.find(t=>t.id===selectedNoteBlock?.linkedTodoId)} block={selectedNoteBlock} blocked={blocked} requests={requests} onSave={saveScheduled} onDelete={()=>deleteBlock(selectedNoteBlock.id)} onClose={closeScheduled}/>}</div>
}
