import { useState } from 'react'
import RequestCard from '../components/RequestCard'
import { getBlockedSlots, getRequests, getStudents, saveRequests, saveStudents, uid } from '../utils/storage'
import { deleteAttachment } from '../utils/fileStorage'
import { getScheduleConflict } from '../utils/timeUtils'
export default function RequestsList({mode='pending'}){
 const [requests,setRequests]=useState(getRequests),[students,setStudents]=useState(getStudents),[notice,setNotice]=useState(null)
 const syncComment=(request,comment)=>setStudents(current=>{const next=current.map(student=>student.id===request.studentProfileId?{...student,consultations:(student.consultations||[]).map(item=>item.meetingRequestId===request.id?{...item,teacherComment:comment}:item),updatedAt:new Date().toISOString()}:student);saveStudents(next);return next})
 const update=(id,changes)=>setRequests(current=>{const request=current.find(r=>r.id===id);if(request?.studentProfileId&&changes.privateTeacherComment!==undefined)syncComment(request,changes.privateTeacherComment);const next=current.map(r=>r.id===id?{...r,...changes,updatedAt:new Date().toISOString()}:r);saveRequests(next);return next})
 const linkStudent=(request,studentId,teacherComment,nextStep)=>{const consultation={id:uid(),date:request.date,time:request.startTime,topic:request.topic,format:request.format,teacherComment,nextStep,meetingRequestId:request.id,createdAt:new Date().toISOString()};setStudents(current=>{const next=current.map(student=>{let consultations=(student.consultations||[]).filter(item=>item.meetingRequestId!==request.id);if(student.id===studentId)consultations=[...consultations,consultation];const dates=consultations.map(item=>item.date).filter(Boolean).sort(),wasPreviousProfile=student.id===request.studentProfileId;return{...student,consultations,lastConsultationDate:dates.at(-1)||(wasPreviousProfile&&student.lastConsultationDate===request.date?'':student.lastConsultationDate),nextStep:student.id===studentId&&nextStep?nextStep:student.nextStep,updatedAt:new Date().toISOString()}});saveStudents(next);return next});update(request.id,{studentProfileId:studentId,privateTeacherComment:teacherComment})}
 const notify=message=>{setNotice(message);setTimeout(()=>setNotice(null),6000)}
 const canApprove=request=>getScheduleConflict({date:request.date,startTime:request.startTime,duration:request.duration,blocked:getBlockedSlots(),requests,excludeRequestId:request.id,checkPast:false,checkPendingExact:false})
 const del=async request=>{if(!confirm('Delete this request permanently?'))return;await Promise.allSettled((request.attachments||[]).map(file=>deleteAttachment(file.id)));if(request.studentProfileId)setStudents(current=>{const next=current.map(student=>student.id===request.studentProfileId?{...student,consultations:(student.consultations||[]).map(item=>item.meetingRequestId===request.id?{...item,meetingRequestId:null}:item),updatedAt:new Date().toISOString()}:student);saveStudents(next);return next});setRequests(current=>{const next=current.filter(r=>r.id!==request.id);saveRequests(next);return next})}
 const items=mode==='approved'?requests.filter(r=>['approved','completed'].includes(r.status)):requests.filter(r=>['pending','rejected'].includes(r.status))
 return <div className="dashboard-content">{notice&&<div className={`page-toast ${notice.ok?'success':'failure'}`}>{notice.text}</div>}<div className="page-heading"><div><span className="eyebrow">{mode==='approved'?'Meeting history':'Inbox'}</span><h1>{mode==='approved'?'Approved meetings':'Meeting requests'}</h1><p>{mode==='approved'?'Upcoming and completed consultations.':'Review, approve, or decline new consultation requests.'}</p><small className="email-destination-note">Automatic messages are sent to the email address provided in the meeting request.</small></div><span className="count-pill">{items.length} {items.length===1?'item':'items'}</span></div>{items.length?<div className="request-grid">{items.map(r=><RequestCard key={r.id} request={r} onUpdate={update} onDelete={del} onNotify={notify} onCanApprove={canApprove} students={students} onLinkStudent={linkStudent}/>)}</div>:<div className="card empty-page"><span className="empty-icon">✓</span><h2>{mode==='approved'?'No approved meetings yet':'No meeting requests'}</h2><p>{mode==='approved'?'Approved and completed meetings will appear here.':'New requests will appear here automatically.'}</p></div>}</div>
}
