import { useEffect, useState } from 'react'
import { CalendarDays, CheckCircle2 } from 'lucide-react'
import { validateBooking } from '../utils/validation'
import { formatLongDate, conflictReason } from '../utils/timeUtils'
import { addRequest, uid } from '../utils/storage'
import { deleteAttachment, saveAttachment } from '../utils/fileStorage'
import { validateAttachments } from '../utils/attachmentValidation'
import AttachmentUploader from './AttachmentUploader'

const initial={name:'',email:'',role:'student',meetingType:'general_consultation',programme:'',topic:'',format:'offline',onlineLink:'',comment:'',duration:30}
export default function BookingForm({selected,setSelected,requests,setRequests,blocked,duration,setDuration}) {
  const [form,setForm]=useState({...initial,duration}), [errors,setErrors]=useState({}), [success,setSuccess]=useState(false),[files,setFiles]=useState([]),[fileError,setFileError]=useState(''),[submitting,setSubmitting]=useState(false)
  useEffect(()=>setForm(current=>({...current,duration})),[duration])
  const update=(e)=>setForm({...form,[e.target.name]:e.target.value})
  const submit=async(e)=>{e.preventDefault(); const data={...form,...selected}; const nextErrors=validateBooking(data),attachmentErrors=validateAttachments(files);const conflict=selected&&conflictReason(selected.date,selected.startTime,form.duration,blocked,requests); if(conflict) nextErrors.slot=conflict;setFileError(attachmentErrors.join(' ')); setErrors(nextErrors); if(Object.keys(nextErrors).length||attachmentErrors.length)return
    setSubmitting(true);const now=new Date().toISOString(),id=uid();let attachments=[];try{for(const file of files)attachments.push(await saveAttachment(file,id))}catch(error){await Promise.allSettled(attachments.map(item=>deleteAttachment(item.id)));setFileError(`Files could not be saved: ${error.message}`);setSubmitting(false);return}const request={...data,duration:Number(data.duration),id,status:'pending',attachments,emailLog:[],privateTeacherComment:'',createdAt:now,updatedAt:now};if(!addRequest(request)){await Promise.allSettled(attachments.map(item=>deleteAttachment(item.id)));setFileError('The request could not be saved in this browser. Please free storage space and try again.');setSubmitting(false);return}setRequests(current=>[{date:request.date,startTime:request.startTime,duration:request.duration,status:request.status},...current]); setSuccess(true); setForm({...initial,duration});setFiles([]);setSubmitting(false); setSelected(null); window.scrollTo({top:0,behavior:'smooth'})
  }
  if(success) return <div className="success-card"><CheckCircle2 size={44}/><span className="eyebrow">Request received</span><h2>Thank you — it’s with the teacher now.</h2><p>Your meeting request has been submitted. You will receive confirmation after the teacher reviews it.</p><button className="btn btn-primary" onClick={()=>setSuccess(false)}>Request another meeting</button></div>
  return <form className="booking-form card" onSubmit={submit}><div className="form-title"><span className="step">2</span><div><span className="eyebrow">Your details</span><h2>Request this meeting</h2></div></div>
    {selected?<div className="selection-summary"><CalendarDays size={20}/><div><strong>{formatLongDate(selected.date)}</strong><span>{selected.startTime} · {form.duration} minutes</span></div></div>:<p className="empty-selection">Select an available time in the calendar to begin.</p>}{errors.slot&&<p className="field-error">{errors.slot}</p>}
    <div className="field-grid"><label>Full name *<input name="name" value={form.name} onChange={update} placeholder="Your full name"/>{errors.name&&<small>{errors.name}</small>}</label><label>Email *<input name="email" type="email" value={form.email} onChange={update} placeholder="you@university.edu"/>{errors.email&&<small>{errors.email}</small>}</label></div>
    <div className="field-grid"><label>Role *<select name="role" value={form.role} onChange={update}><option value="student">Student</option><option value="ma_student">MA student</option><option value="colleague">Colleague</option><option value="other">Other</option></select></label><label>Meeting type *<select name="meetingType" value={form.meetingType} onChange={e=>{update(e);if(e.target.value!=='thesis_supervision'){setFiles([]);setFileError('')}}}><option value="general_consultation">General consultation</option><option value="thesis_supervision">Thesis supervision</option><option value="course_question">Course-related question</option><option value="administrative_issue">Administrative issue</option><option value="research_discussion">Research discussion</option><option value="other">Other</option></select></label></div>
    <label>Programme or department<input name="programme" value={form.programme} onChange={update} placeholder="Optional"/></label>
    <div className="field-grid"><label>Duration *<select name="duration" value={form.duration} onChange={e=>{update(e);setDuration(Number(e.target.value));setSelected(null)}}>{Array.from({length:11},(_,i)=>10+i*5).map(n=><option key={n}>{n}</option>)}</select>{errors.duration&&<small>{errors.duration}</small>}</label><label>Format *<select name="format" value={form.format} onChange={update}><option value="offline">Offline</option><option value="online">Online</option></select></label></div>
    {form.format==='online'&&<label>Online meeting link *<input name="onlineLink" value={form.onlineLink} onChange={update} placeholder="https://meet.google.com/…"/>{errors.onlineLink&&<small>{errors.onlineLink}</small>}</label>}
    <label>Meeting topic *<input name="topic" value={form.topic} onChange={update} placeholder="What would you like to discuss?"/>{errors.topic&&<small>{errors.topic}</small>}</label>
    <label>Comment<textarea name="comment" value={form.comment} onChange={update} rows="3" placeholder="Anything else the teacher should know?"/></label>
    {form.meetingType==='thesis_supervision'&&<AttachmentUploader files={files} setFiles={setFiles} error={fileError} setError={setFileError}/>}<button className="btn btn-primary btn-wide" disabled={!selected||submitting}>{submitting?'Saving request…':'Submit meeting request'}</button><p className="form-note">Submitting a request does not automatically confirm the meeting.</p>
  </form>
}
