import { useState } from 'react'
import { Calendar, Clock, Copy, ExternalLink, Mail, Send, Trash2, UserRound } from 'lucide-react'
import StatusBadge from './StatusBadge'
import EmailStatusBadge from './EmailStatusBadge'
import EmailHistory from './EmailHistory'
import MessagePreviewModal from './MessagePreviewModal'
import SupervisionFilesSection from './SupervisionFilesSection'
import LinkMeetingToStudent from './LinkMeetingToStudent'
import { formatLongDate } from '../utils/timeUtils'
import { approvalMessage, rejectionMessage, reminderMessage } from '../utils/messageTemplates'
import { sendApprovalEmail, sendRejectionEmail, sendReminderEmail } from '../utils/emailService'

const messageDetails={approval:{subject:'Meeting request approved',body:approvalMessage},rejection:{subject:'Meeting request update',body:rejectionMessage},reminder:{subject:'Reminder: upcoming meeting',body:reminderMessage}}
const senders={approval:sendApprovalEmail,rejection:sendRejectionEmail,reminder:sendReminderEmail}
export default function RequestCard({request,onUpdate,onDelete,onNotify,onCanApprove,students=[],onLinkStudent}){
  const [copied,setCopied]=useState(false),[note,setNote]=useState(request.privateTeacherComment||request.privateNote||''),[notice,setNotice]=useState(null),[sending,setSending]=useState(false),[preview,setPreview]=useState(null)
  const logs=request.emailLog||[],lastLog=logs.at(-1)
  const copy=async text=>{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),1800)}
  const send=async(type,statusChange)=>{if(statusChange==='approved'){const conflict=onCanApprove?.(request);if(conflict){const message={ok:false,text:`Cannot approve this request: ${conflict}`};setNotice(message);onNotify?.(message);return}}setSending(true);setNotice(null);if(statusChange)onUpdate(request.id,{status:statusChange});const result=await senders[type]({...request,status:statusChange||request.status});onUpdate(request.id,{emailLog:[...logs,result.log]});setSending(false);setPreview(null);const message=result.success?{ok:true,text:`${type[0].toUpperCase()+type.slice(1)} email sent to ${request.email}.`}:{ok:false,text:`${statusChange?`Request ${statusChange}, but `:''}the email could not be sent. ${result.error} You can copy the message manually.`};setNotice(message);onNotify?.(message)}
  const openPreview=type=>setPreview({type,subject:messageDetails[type].subject,body:messageDetails[type].body(request)})
  const generated=request.status==='rejected'?rejectionMessage(request):['approved','completed'].includes(request.status)?(request.status==='completed'?reminderMessage(request):approvalMessage(request)):''
  return <article className="request-card"><div className="request-card-head"><div className="request-person"><div className="request-avatar">{request.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><h3>{request.name}</h3><a href={`mailto:${request.email}`}>{request.email}</a></div></div><StatusBadge status={request.status}/></div>
    <div className="message-recipient"><Mail size={14}/><span>Messages go to <strong>{request.email}</strong>{lastLog&&<small>Last: {lastLog.type} · {new Intl.DateTimeFormat('en',{dateStyle:'medium',timeStyle:'short'}).format(new Date(lastLog.sentAt))}</small>}</span>{lastLog&&<EmailStatusBadge status={lastLog.status}/>}</div>
    <div className="request-meta"><span><Calendar size={16}/>{formatLongDate(request.date)}</span><span><Clock size={16}/>{request.startTime} · {request.duration} min</span><span><UserRound size={16}/>{request.role.replace('_',' ')}{request.programme?` · ${request.programme}`:''}</span><span><Mail size={16}/>{request.format}</span></div>
    <div className="request-topic"><small>Meeting topic · {request.meetingType.replaceAll('_',' ')}</small><strong>{request.topic}</strong>{request.comment&&<p>“{request.comment}”</p>}{request.onlineLink&&<a href={request.onlineLink} target="_blank" rel="noreferrer">Open meeting link <ExternalLink size={14}/></a>}</div>
    {request.meetingType==='thesis_supervision'&&<SupervisionFilesSection attachments={request.attachments} onDeleted={id=>onUpdate(request.id,{attachments:request.attachments.filter(file=>file.id!==id)})}/>}<label className="note-field">Private teacher comment<textarea rows="2" value={note} onChange={e=>setNote(e.target.value)} onBlur={()=>onUpdate(request.id,{privateTeacherComment:note})} placeholder="Only you can see this comment"/></label>{(request.role==='ma_student'||request.meetingType==='thesis_supervision')&&<LinkMeetingToStudent request={request} students={students} onLink={onLinkStudent}/>} 
    {notice&&<div className={`action-notice ${notice.ok?'success':'failure'}`}>{notice.text}</div>}{generated&&<div className="generated-message"><span>Message ready to send</span><button onClick={()=>copy(generated)}><Copy size={15}/>{copied?'Copied':'Copy message'}</button></div>}<EmailHistory logs={logs}/>
    <div className="request-actions">{request.status==='pending'&&<><button className="btn btn-primary btn-sm" disabled={sending} onClick={()=>send('approval','approved')}>Approve & email</button><button className="btn btn-danger-soft btn-sm" disabled={sending} onClick={()=>send('rejection','rejected')}>Reject & email</button></>}{request.status==='approved'&&<><button className="btn btn-secondary btn-sm" onClick={()=>onUpdate(request.id,{status:'completed'})}>Mark completed</button><button className="btn btn-ghost btn-sm" disabled={sending} onClick={()=>send('reminder')}><Send size={14}/>Send reminder</button></>}<button className="btn btn-ghost btn-sm" onClick={()=>openPreview(request.status==='rejected'?'rejection':request.status==='pending'?'approval':'reminder')}>Preview</button>{lastLog?.status==='failed'&&<button className="btn btn-ghost btn-sm" disabled={sending} onClick={()=>send(lastLog.type)}>Resend email</button>}<button className="icon-btn delete" onClick={()=>onDelete(request)} title="Delete"><Trash2 size={17}/></button></div>
    {preview&&<MessagePreviewModal subject={preview.subject} body={preview.body} onClose={()=>setPreview(null)} onCopy={()=>copy(preview.body)} sending={sending} onSend={()=>send(preview.type,request.status==='pending'?(preview.type==='rejection'?'rejected':'approved'):undefined)}/>}</article>
}
